<header class="header">
    <div class="container">
        <div class="logo">
            <a href="<?php echo $site->siteUrl(); ?>" style="color: inherit; text-decoration: none;">MegaLOD</a>
        </div>
        <nav class="nav">
            <a href="<?php echo $this->url('site/add-triplestore', ['site-slug' => $site->slug()]); ?>">Main Menu</a>
            <a href="<?php echo $this->url('site/add-triplestore/search', ['site-slug' => $site->slug()], ['query' => ['query' => 'excavation', 'type' => 'item_sets']]); ?>">Collections</a>
            <a href="<?php echo $this->url('site/add-triplestore/search', ['site-slug' => $site->slug()]); ?>">Map</a>
            <a href="<?php echo $this->url('site/add-triplestore/sparql', ['site-slug' => $site->slug()]); ?>">SPARQL Endpoint</a>
            <a href="<?php echo $this->url('site/add-triplestore/about-us', ['site-slug' => $site->slug()]); ?>">About Us</a>
            <?php if ($this->identity()): ?>
                <?php if ($this->identity()->getRole() === 'guest'): ?>
                    <a href="<?php echo $this->url('site/add-triplestore/dashboard', ['site-slug' => $site->slug()]); ?>" class="user-name">
                        <?php echo $this->identity()->getName(); ?>
                    </a>
                <?php else: ?>
                    <a href="<?php echo $this->url('admin/id', ['controller' => 'user', 'id' => $this->identity()->getId()]); ?>" class="user-name">
                        <?php echo $this->identity()->getName(); ?>
                    </a>
                <?php endif; ?>
            <?php endif; ?>
        </nav>
    </div>
</header>